title:            Andrew Bauman
description:      Andrew Bauman's home page on the World Wide Web.
url:              https://drewsiph.dev
permalink:        /posts/:title
timezone:         America/New_York
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: true
  pages:
    output: true
  stories:
    output: true
i18n:
  en-US:
    accessibility: Accessibility statement
    source: View source
  es-ES:
    Travel: Viajar
    Animals: Animales
    Books: Libros
    Cook: Cocinar
    Plants: Plantas
    24h: Hoy
    Mails: Correo
    Friends: Amigos
    Self: Yo Mismo
    Polaroid: Polaroid
    Chat: Charlar
    Hobby: Pasatiempos
    accessibility: Accessibilidad
    source: Ver código fuente
    ATH: ATH
    LA: LA
    PBI: PBI
    PHL: PHL
    Life: Vida
include: [".well-known"]
markdown: kramdown
commonmark:
  options: ["UNSAFE", "HARDBREAKS"]
  extensions: ["strikethrough", "autolink", "table"]
recent_date: "2025/7/16"
